import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignIn,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import HeaderPage from "./components/header";
import Navbar from "./components/Navbar";
import MainNavbar from "./components/MainNavbar";
import Footer from "./components/footer";
import { GlobalProvider } from "./components/GlobleProvider";
import { CartProvider } from "./context/CartContaxt";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
      <header className="flex justify-between">
          <h1>Comforty</h1>
          <UserButton showName />
        </header>
    
      <SignedOut>
            <SignIn routing="hash"/>
          </SignedOut>
          <SignedIn>
           
           
      <CartProvider>
            <HeaderPage />
            <Navbar >
           
            </Navbar>
            <MainNavbar />
        {children}
        <Footer />
          </CartProvider>
          </SignedIn>
        </body>
    </html>
    </ClerkProvider>
  );
}